version: '3'

services:
  nginx:
    build: .
    network_mode: "host"
    #  restart: "always"
    volumes:
      - ./config/certbot/conf:/etc/letsencrypt
      - ./config/certbot/www:/var/www/certbot
    environment:
    - BASE_DOMAIN=${BASE_DOMAIN}
    - TYPE=frontend
  certbot:
    image: certbot/certbot
    environment:
      - TYPE=certbot
    volumes:
      - ./config/certbot/conf:/etc/letsencrypt
      - ./config/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
